url: "https://mechatronicsystems-group.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MechatronicSystems.Group" # the name of your site, e.g. ACME Corp.
description: "A mechatronics engineering research group in the Deptment Mechanical Engineering, UCT "
