menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'code', url: 'https://github.com/MechatronicSystems-Group'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Arnold Pretorius', title: 'Researcher - Control Engineering, State Estimation, Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 3479', email: 'arnold.pretorius@uct.ac.za', office: 'R215.2 EM Building, UCT', image: 'assets/img/people/Arnold.png', url: 'arnold-pretorius'}
- {name: 'Leanne Raw', title: 'Researcher - Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 9111', email: 'leanne.raw@uct.ac.za', office: 'R212 EM Building, UCT', image: 'assets/img/people/Leanne.png', url: 'leanne-raw'}
- {name: 'James Hepworth', title: 'Researcher - Embedded Systems, Instrumentation', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 4810', email: 'james.hepworth@uct.ac.za', office: 'R215.3 EM Building, UCT', image: 'assets/img/people/James.png', url: 'james-hepworth'}

projects:
- {name: 'Jominy End Quench Imaging', url: 'jominy-quench', status: 'In progress'}
- {name: 'SEM Hot Stage Design', url: 'sem-hot-stage', status: 'Open for applications'}
- {name: 'Antarctic Wind Sensor Design', url: 'wind-sensor', status: 'In progress'}
- {name: 'Sea-Ice Field Extraction', url: 'sea-ice-LiDAR', status: 'In progress'}
- {name: 'System identification and control design of a quadcopter', url: 'low-cost-quad', status: 'In progress'}
- {name: 'Flight Controller Design', url: 'flight-controller', status: 'In progress'}
- {name: 'Quadcopter Pose Estimation', url: 'quad-pose', status: 'In progress'}

social:
- {icon: 'github', link: 'https://github.com/MechatronicSystems-Group'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'instagram', link: 'https://instagram.com/'}

contacts:
- {name: 'MechantronicSystems.Lab',  department: 'Mechanical Engineering', institution: 'University of Cape Town', institution_address: 'MechantronicSystems.Lab, Duncan McMillan Laboratory, 217 Library Road, Rondebosch, Cape Town, 7700', phone: '+27 21 650 4810', email: 'mmtstream@uct.ac.za'}
