menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'vacwork', url: '/vacwork'}
- {name: 'research', url: '/projects'}
- {name: 'code', url: 'https://github.com/MechatronicSystems-Group'}
- {name: 'contact', url: '/contact'}

staff:
- {name: 'Arnold Pretorius', title: 'Researcher - Control Engineering, State Estimation, Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 3479', email: 'arnold.pretorius@uct.ac.za', office: 'R215.2 EM Building, UCT', image: 'assets/img/people/Arnold.png', url: 'arnold-pretorius'}
- {name: 'Leanne Raw', title: 'Researcher - Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 9111', email: 'leanne.raw@uct.ac.za', office: 'R212 EM Building, UCT', image: 'assets/img/people/Leanne.png', url: 'leanne-raw'}
- {name: 'James Hepworth', title: 'Researcher - Embedded Systems, Instrumentation', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 4810', email: 'james.hepworth@uct.ac.za', office: 'R215.3 EM Building, UCT', image: 'assets/img/people/James.png', url: 'james-hepworth'}

projects:
- {name: 'System Identification and Control Design of a Quadcopter', url: 'low-cost-quad', status: 'In progress', student: 'Luke Richardson', studentType: 'MSc student'}
- {name: 'Embedded Systems Design of a Quadcopter', url: 'flight-controller', status: 'In progress', student: 'Daniel Fraser', studentType: 'MSc student'}
- {name: 'Pose Estimation and Trajectory Generation of a Quadcopter', url: 'quad-pose', status: 'In progress', student: 'Alyssa Ramwell', studentType: 'MSc student'}
- {name: 'Mechanical design and implementation of a pole climbing robot for rapid surveillance', url: 'pole-robot', status: 'In progress', student: 'Willis de Ronde', studentType: 'MSc student'}
- {name: 'Design of a low-cost, vision-based motion capture system for use in rigid-body pose estimation', url: 'motion-capture', status: 'In progress', student: 'Zak Meyer', studentType: 'MSc student'}
- {name: 'Modelling, design, and prototyping of a coaxial variable-tilt multicopter', url: 'tilt-rotor', status: 'In progress', student: 'Guy Hasewinkel', studentType: 'MSc student'}
- {name: 'Autonomous landing of a quadcopter platform on a sea vessel during rough sea state conditions', url: 'quad-sea', status: 'In progress', student: 'Dylan Fanner', studentType: 'MSc student'}
- {name: 'Jominy End Quench Imaging', url: 'jominy-quench', status: 'Open for applications', student: 'TBD', studentType: 'MSc student'}
- {name: 'SEM Hot Stage Design', url: 'sem-hot-stage', status: 'Open for applications', student: 'TBD', studentType: 'MSc student'}
- {name: 'Antarctic Wind Sensor Design', url: 'wind-sensor', status: 'Open for applications', student: 'TBD', studentType: 'MSc student'}
- {name: 'Sea-Ice Field Extraction', url: 'sea-ice-LiDAR', status: 'Open for applications', student: 'TBD', studentType: 'MSc student'}

vacwork_projects:
- {name: 'Design and prototyping of a UAV attitude test rig', url: 'attitude-test-rig', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Design and assembly of a flight test space for small UAVs', url: 'flight-test-space', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Design and assembly of a Stewart platform', url: 'stewart-platform', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Investigating the efficacy of OpenMV cameras for use in pose estimation', url: 'openmv-camera-pose-estimation', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Mechanical design and prototyping of a micro UAV', url: 'micro-uav', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Investigating code deployment from MATLAB/Simulink using PX4 software', url: 'px4-design', status: 'Open for applications', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Design of a 3D printer filament recycling system', url: '3d-printer-filament-recycling', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Firmware development for a BMI088 IMU', url: 'firmware-development-BMI088', status: 'In progress', student: 'TBD', studentType: 'Vac work student'}
- {name: 'Software and user interface design for a propulsion rig', url: 'propulsion-rig', status: 'In progress', student: 'Michael Thomson', studentType: 'Vac work student'}

funders:
- {image: 'assets/img/logos/csir.jpeg', link: 'https://www.csir.co.za/'}
- {image: 'assets/img/logos/SAIMI.jpg', link: 'https://saimi.co.za/'}

contacts:
- {name: 'MechatronicSystems.Lab',  department: 'Mechanical Engineering', institution: 'University of Cape Town', institution_address: 'MechatronicSystems.Lab, Duncan McMillan Laboratory, 217 Library Road, Rondebosch, Cape Town, 7700', phone: '+27 21 650 4810', email: 'mechatronicsystems.group@uct.ac.za'}

