menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'code', url: 'https://github.com/MechatronicSystems-Group'}
- {name: 'contact', url: '/contact'}

staff:
- {name: 'Arnold Pretorius', title: 'Researcher - Control Engineering, State Estimation, Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 3479', email: 'arnold.pretorius@uct.ac.za', office: 'R215.2 EM Building, UCT', image: 'assets/img/people/Arnold.png', url: 'arnold-pretorius'}
- {name: 'Leanne Raw', title: 'Researcher - Robotics', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 9111', email: 'leanne.raw@uct.ac.za', office: 'R212 EM Building, UCT', image: 'assets/img/people/Leanne.png', url: 'leanne-raw'}
- {name: 'James Hepworth', title: 'Researcher - Embedded Systems, Instrumentation', department: 'Mechanical Engineering', institution: 'UCT', phone: '+27 21 650 4810', email: 'james.hepworth@uct.ac.za', office: 'R215.3 EM Building, UCT', image: 'assets/img/people/James.png', url: 'james-hepworth'}

students:
- {name: 'Zak Meyer', title: '3rd-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'motion-capture'}
- {name: 'Willis de Ronde', title: '3rd-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'pole-robot'}
- {name: 'Guy Hasewinkel', title: '2nd-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'tilt-rotor'}
- {name: 'Dylan Fanner', title: '1st-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'quad-sea'}
- {name: 'Luke Richardson', title: '1st-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'low-cost-quad'}
- {name: 'Alyssa Ramwell', title: '1st-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'quad-pose'}
- {name: 'Daniel Fraser', title: '1st-year MSc Student', department: 'Mechanical Engineering', institution: 'UCT', url: 'flight-controller'}

projects:
- {name: 'Jominy End Quench Imaging', url: 'jominy-quench', status: 'In progress', student: '?'}
- {name: 'SEM Hot Stage Design', url: 'sem-hot-stage', status: 'Open for applications', student: '?'}
- {name: 'Antarctic Wind Sensor Design', url: 'wind-sensor', status: 'In progress', student: '?'}
- {name: 'Sea-Ice Field Extraction', url: 'sea-ice-LiDAR', status: 'In progress', student: '?'}
- {name: 'System Identification and Control Design of a Quadcopter', url: 'low-cost-quad', status: 'In progress', student'Luke Richardson'}
- {name: 'Embedded Systems Design of a Quadcopter', url: 'flight-controller', status: 'In progress', student: 'Daniel Fraser'}
- {name: 'Pose Estimation and Trajectory Generation of a Quadcopter', url: 'quad-pose', status: 'In progress', student: 'Alyssa Ramwell'}
- {name: 'Mechanical design and implementation of a pole climbing robot for rapid surveillance', url: 'pole-robot', status: 'In progress', student: 'Willis de Ronde'}
- {name: 'Design of a low-cost, vision-based motion capture system for use in rigid-body pose estimation', url: 'motion-capture', status: 'In progress', student: 'Zak Meyer'}
- {name: 'Modelling, design, and prototyping of a coaxial variable-tilt multicopter', url: 'tilt-rotor', status: 'In progress', student: 'Guy Hasewinkel'}
- {name: 'Autonomous landing of a quadcopter platform on a sea vessel during rough sea state conditions', url: 'quad-sea', status: 'In progress', student: 'Dylan Fanner'}

social:
- {icon: 'github', link: 'https://github.com/MechatronicSystems-Group'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'instagram', link: 'https://instagram.com/'}

contacts:
- {name: 'MechatronicSystems.Lab',  department: 'Mechanical Engineering', institution: 'University of Cape Town', institution_address: 'MechatronicSystems.Lab, Duncan McMillan Laboratory, 217 Library Road, Rondebosch, Cape Town, 7700', phone: '+27 21 650 4810', email: 'mechatronicsystems.group@uct.ac.za'}

